version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "5672:5672"#normal rabbitmq port
      - "15672:15672"#this is the management port
        
  rabbitmq:
    container_name: basketdb
    restart: always
    ports:
      - "6379:63779"
        
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDataBaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    volumes:
    - ${HOME}/.microsoft/usersecrets/:/root/.microsft/usersecrets
    - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8000:80"
        
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379" #container_name:PORT
      - "EventBus:HostName=rabbitmq" #same configuration in appSettings
    depends_on:
      - basketdb
      - rabbitmq
    volumes:
    - ${HOME}/.microsoft/usersecrets/:/root/.microsft/usersecrets
    - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8001:80"

